help:
	@grep '###' Makefile | grep -v grep |sed -e 's/####//'
cart: ### setup cart component
	@bash components/cart.sh
catalogue: ### setup catalogue component
	@bash components/catalogue.sh
user: ### setup user component
	@bash components/user.sh
shipping: ### setup shipping component
	@bash components/shipping.sh
mysql: ### setup mysql component
	@bash components/mysql.sh
mongodb: ### setup mongodb component
	@bash components/mongodb.sh
payment: ### setup payment component
	@bash components/payment.sh
frontend: ### setup frontend component
	@bash components/frontend.sh
robbitmq: ### setup robbitmq component
	@bash components/robbitmq.sh
redis: ### setup redis component
	@bash components/redis.sh

